/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ParticuliersRouteImport } from './routes/particuliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticuliersRoute = ParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/particuliers': typeof ParticuliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/entreprises'
    | '/mentions-legales'
    | '/particuliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/entreprises'
    | '/mentions-legales'
    | '/particuliers'
  id:
    | '__root__'
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/entreprises'
    | '/mentions-legales'
    | '/particuliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EntreprisesRoute: typeof EntreprisesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ParticuliersRoute: typeof ParticuliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particuliers': {
      id: '/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof ParticuliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EntreprisesRoute: EntreprisesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ParticuliersRoute: ParticuliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
